### PR TITLE
Some small UI changes

### PR DESCRIPTION
**Pull request by xi**
I have some more changes for #967 locally, but I am not pleased with most of them yet. So this is a small collection of bits and bobs that can already be merged.

### CODE REVIEW

**Comment by protz** [comment]
Looks good, thanks!

**Comment by xi** [comment]
That was fast!

**Comment by protz** [comment]
I need to keep up with your pull requests and make sure they're treated 
with the consideration they deserve! ;-)

**Comment by protz** [comment]
I think this pull request or another one broke the contact tooltip...

**Comment by protz** [comment]
That is, after hitting "show details"...

**Comment by xi** [comment]
> I think this pull request or another one broke the contact tooltip...

What exactly seems to be broken? For me it seems to work just fine.

**Comment by protz** [comment]
image

When I hover over the contacts in that view, I no longer get a contact tooltip... but perhaps it was already the case before?

**Comment by xi** [comment]
> but perhaps it was already the case before?

Yes, I think so. II checked it on 00f9ec002088780e910668dceea7a352488c91e6 and the behavior was the same as on master.

**Pull request merged**
