### PR TITLE
Update 'more' link and tooltip UI

### PR DESCRIPTION
**Pull request by shirosaki**
Implement 'more' link and tooltip UI based on the mockups in #967.

I tried to implement the UI partially. What do you think?

ui

### CODE REVIEW

**Comment by msprotz** [comment]
Hi Hiroshi,

I just took a look at this. I think it's a really good start! Some remarks:
- the vertical dots are not really aligned on my computer; 
image you probably need to use some different CSS to achieve the desired effect
- reply became "Reply"; the case is not consistent with the rest of the UI
- the images in the menu are not aligned vertically (`vertical-align: middle` ?) 
image
- the images in the menu don't look good on my hidpi screen; do you have an SVG source for them or a set of alternative, 2x resolution images?

Thanks and a merry christmas!

Jonathan

**Comment by shirosaki** [comment]
Thank you for review!

I fixed vertical align issues to use `vertical-align: middle`.
I changed the case small as the rest of the UI.
I don't have SVG or high resolution icons. I made icon images from the jpeg mockups of @elioqoshi by copy and modification. Does @elioqoshi have it?

**Comment by shirosaki** [comment]
I found that the icons are from http://www.flaticon.com/authors/google.
So I've replaced icons with SVG.

**Comment by protz** [comment]
@shirosaki : I haven't forgotten about this pull request, I'm just really busy right now. I'll do a proper review in early February once I'm back in Seattle.

Thanks for understanding!

**Comment by protz** [comment]
(But overall I think it's good and I'll end up integrating it. Feel free to keep working on this if you feel so inclined...)

**Comment by xi** [comment]
This is probably dependent on the theme, but for me the text changes color (from dark to light) on hover. It would be nice if the icon always had the same color as the text. This should be possible using icon fonts.

**Comment by xi** [comment]
These changes have been incorporated into #1141, so this pull request can be closed now.

**Comment by xi** [comment]
Thanks to @shirosaki for the research and inspiration!

**Pull request closed without merging**
