### PR TITLE
[WIP] Introduce more SVG icons

### PR DESCRIPTION
**Pull request by fllp**
Replace old icons/text links with new icons according to designs from #967.

### polishing needed:

- contact popup
- attachment area

new-icons

### CODE REVIEW

**Comment by elioqoshi** [comment]
That's great improvement! Awesome stuff!

**Comment by fllp** [comment]
Thanks! It does need some tweaking though.
Especially the functionality of the 'more' button in the contact popup needs to be changed. Right now its just new icons.

I think the attachment area could be rebuilt using CSS table-display to align header, thumbnail and file info properly. Should be an extra branch though, since adjustment of the XHTML sources would be needed.

**Comment by protz** [comment]
I'm merging this -- great stuff! Apologies about the delay, I had a series of paper submission deadlines recently. I hope that doesn't deter you from pursuing further followup fixes!

**Comment by fllp** [comment]
Don't worry, my motivation is unbroken so far. Next thing would be
fixing minor glitches, like the options popup menu not being properly
aligned.
Although, it might now in turn take some time on my end as i too face a
submission deadline ;-)


Am 12.03.2017 um 01:46 schrieb Jonathan Protzenko:

**Pull request merged**
