### PR TITLE
Reintroduce between column

### PR DESCRIPTION
**Pull request by pianoslum**
This should reintroduce the 'between'-column, which is indeed better than the correspondents-column btw.

Incidentally, I updated stdlib

### CODE REVIEW

**Comment by pianoslum** [comment]
I forgot: The between-column's label is displayed in English for me, although my lang is set to German. Did I forget to revert something or is this expected?

**Comment by msprotz** [comment]
https://github.com/protz/thunderbird-conversations/issues/622 ?

**Comment by pianoslum** [comment]
No, if so, more names belonging to TB itself would be english.
I just saw that "Reply" etc. on Conversations side is still English - I recall that you said that you only add the translations before publishing? Could that be it?

**Comment by msprotz** [comment]
oh! perhaps it is, yes -- I haven't refreshed the translations in a long while, and they're not enabled on the -master branch

**Comment by pianoslum** [comment]
Then it should be ok - we just have to be careful that the "between"-translations are included again :-)

**Pull request merged**
