### PR TITLE
UI: round tags and flat buttons

### PR DESCRIPTION
**Pull request by xi**
This adds some more UI changes for #967.

Next up I will take care of icons.

### CODE REVIEW

**Comment by protz** [comment]
Thanks, this looks good.

What about the menu?

image

Was wondering if the little triangle ought to change color at some point.

**Comment by xi** [comment]
> Was wondering if the little triangle ought to change color at some point.

Oops! That was a regression introduced in f8cb99b. I pushed a fix on top of #1141 to avoid merge conflicts.

**Comment by protz** [comment]
Excellent, thanks.

**Comment by elioqoshi** [comment]
Happy to see progress here :)

**Pull request merged**
