### PR TITLE
Add BzAPI definition for bugs.kde.org

### LINKED ISSUE #1271: BzAPI for bugs.kde.org
Hi,

The notice I got in Thunderbird led me to the [wiki](https://github.com/protz/thunderbird-conversations/wiki/BzConversations) page and I can confirm that the API endpoint of bugs.kde.org is just `https://bugs.kde.org/rest`.

For instance, I could run
```
curl https://bugs.kde.org/rest/bug/300000
```
...to fetch the details of this bug. And they also allow generating API keys at https://bugs.kde.org/userprefs.cgi?tab=apikey

### PR DESCRIPTION
**Pull request by Frederick888**
Closes #1271

### CODE REVIEW

**Comment by msprotz** [comment]
Thanks for the pull request! Have you confirmed that this works for you?

**Comment by Frederick888** [comment]
@msprotz Well, it turns out that they are now using the new [native REST APIs](https://wiki.mozilla.org/Bugzilla:REST_API) instead of BzAPI so it didn't work out of the box. I tried the BzAPI [compatibility layer](https://wiki.mozilla.org/Bugzilla:BzAPI:CompatLayer) but it seems that they've dropped this functionality as well.

BUT, the old and new APIs are actually rather similar and the new API still supports cookie-based authentication. So I have just pushed another commit to make the extension compatible with the new API (a bit hacky tho). I have manually tested it by adding a new comment to an issue.

Is commenting the only integration we have for Bugzilla?

**Comment by msprotz** [comment]
Can we upgrade everyone to use the new REST APIs? I think the BzAPI is going to be retired anyhow, and I would suspect Mozilla's Bugzilla also has a REST endpoint. See #1116  -- that way, your patch would be even simpler and could retire the old code :)

**Comment by Frederick888** [comment]
@msprotz To me it's like why not. And it would allow us to provide general Bugzilla support as well since the API URL will be consistently `http[s]://bugzilla.example.com/rest` (of course an exception table can be maintained).

If you could provide some mentoring I guess I can take the task.

**Comment by protz** [comment]
Hello @Frederick888  -- got back from vacations and catching up.

My suggestion would be to just take your patch, and remove the "type" field, and make everything go through the newer REST API. In other words: don't if-then-else on whether it's a bzapi or REST endpoint, and assume that it is always REST.

What do you think? This should be a minor change to your patch, and I believe would be a good way to bring Conversations to use the newer APIs.

**Comment by Standard8** [comment]
This never seemed to get completed and we're going to be dropping the bugzilla integration soon.

**Pull request closed without merging**
