### PR TITLE
Fixing issue #1091

### PR DESCRIPTION
**Pull request by daesters**
Fixes issue #1091

### CODE REVIEW

**Comment by protz** [comment]
Sorry -- I just now saw this.

Before merging, I'd like to understand:
- is the function gone?
- is the function no longer relevant, or does it throw an exception?
- isn't it better to wrap it in a try-catch block?
- is this codepath exercised only when in a tab?

Thanks,

Jonathan

**Comment by xi** [comment]
This may come from my comment at https://github.com/protz/thunderbird-conversations/issues/1091#issuecomment-227230417. Some people reported that it helps, but I strongly advise against merging it without a better understanding of the problem.

That said, #1091 is a real dealbreaker and I would really like if it was fixed soon.

**Comment by daesters** [comment]
@protz Sorry, I didn't reply earlier.
As @xi says, it was his comment which pointed to the solution. I don't know the details about the function, whether it is obsolet now or an exception would be better. I'm not yet deep into addons programmming of thunderbird.
I just implemented it, because, #1090  "is a real dealbreaker",as @xi rightly says

**Comment by protz** [comment]
I've investigated and pushed a proper fix. Thanks! (Pre-release build at https://jonathan.protzenko.fr/thunderbird-conversations/)

**Comment by Standard8** [comment]
For reference, the proper fix was https://github.com/protz/thunderbird-conversations/commit/f2252db9bda1c2d19f5e1a47506302fae9867056

**Pull request closed without merging**
